@Metadata.allowExtensions: true
@EndUserText.label: 'Asset Value'
@AccessControl.authorizationCheck: #NOT_REQUIRED
define view entity ZC_TGRC_ASSET_VAL  
  as projection on ZR_TGRC_ASSET_VAL
{
 
  key AssetUuid,
  key AssetValueUuid,
  AssetValueExternal,
  ListId,
  ValueId,
  RecordtypDesc,
  AmountOfInterest,
  AmountOfInterestChangeAmt,
  ApmmInsuredValue,
  AssetValue,
  AssetCategory,
  AssetStatus,
  AssetValueFormula,
  AssetValueOnl,
  AssetValue100Percent,
  AssetVal100PercntChngAmt,
  AssetValueChangeAmount,
  AssetValueForInterest,
  AssetValForInterestchngAmt,
  AssetName,
  AssetValueStatus,
  BusinessInterruption,
  BusinessInterruptionChngAmt,
  BusinessUnit,
  CargoValue,
  ContentEquipment,
  CranesAndHandlingEquipment,
  CranesHandlingEquipChngAmt,
  Createdb,
  Currency,
  CurrencyCode,
  DeadweightTonnage,
  DeclaredValue,
  Deductible,
  Equipment,
  Flag,
  FlagId,
  GrossTonnage,
  Hierarchy,
  HullValue,
  HullValueChangeAmount,
  Infrastructure,
  Lastmodifiedb,
  MostRecent,
  RkNextPtr,
  OtliValue,
  OtliValueChangeAmount,
  HierarchyNode,
  OwnerId,
  PIClubNew,
  PIClub,
  RkPrevPtr,
  PropHandlingEquipChngAmt,
  Property,
  PropertyAndHandlingEquip,
  PropertyChangeAmount,
  PvSTOnly,
  RenewalAssignment,
  Revenue,
  RkErrorDetail,
  RkErrorFlag,
  RkGenAssetValuesPid,
  RkPendingVoidCount,
  RkPidConstructor,
  Status,
  TotalInsuredValue,
  TotalInsuredValueChngAmt,
  Utilisation,
  Utilization,
  UtilizationChangeAmount,
  ValuationDate,
  ValuationEndDate,
  VarianceNotes,
  VolumeTons,
  WarValue,
  WarValueChangeAmount,
  WarehouseOfficeBuildings,
  Createdby,
  Createdat,
  Lastchangedby,
  Lastchangedat,
  _Asset: redirected to parent ZC_TGRC_ASSET
  
}
